// <auto-generated />
using System;
using CrescerSaudavel.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrescerSaudavel.Api.Migrations
{
    [DbContext(typeof(CrescerSaudavelDbContext))]
    [Migration("20251201013510_AddNutrientParametersToDieta")]
    partial class AddNutrientParametersToDieta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("core")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Alimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EhPreTermo")
                        .HasColumnType("bit");

                    b.Property<double>("EnergiaKcalPor100")
                        .HasColumnType("float");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<int?>("IdadeMaximaSemanas")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMinimaSemanas")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProteinaGPor100")
                        .HasColumnType("float");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Alimento", "nutricao");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.AuditoriaAcessoPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RecemNascidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResumoDadosAcessados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("bit");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RecemNascidoId", "CriadoEm");

                    b.HasIndex("UsuarioId", "CriadoEm");

                    b.ToTable("AuditoriaAcessoPaciente", "interoperabilidade");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstaturaCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PerimetroCefalicoCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<Guid>("RecemNascidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ZScoreAltura")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("ZScorePerimetro")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("ZScorePeso")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.HasIndex("RecemNascidoId");

                    b.ToTable("Consulta", "clinica");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Dieta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<double>("FrequenciaHoras")
                        .HasColumnType("float");

                    b.Property<double?>("MetaProteinaGKg")
                        .HasColumnType("float");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PesoReferenciaKg")
                        .HasColumnType("float");

                    b.Property<Guid>("RecemNascidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("TaxaEnergeticaKcalKg")
                        .HasColumnType("float");

                    b.Property<string>("ViaAdministracao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecemNascidoId");

                    b.ToTable("Dieta", "nutricao");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.DietaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("EnergiaTotalKcal")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("ProteinaTotalG")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("DietaId");

                    b.ToTable("DietaItem", "nutricao");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.GrupoSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupoSaude", "core");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.PacienteIdentificador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<Guid>("RecemNascidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SistemaEmissor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIdentificador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TipoIdentificador", "Valor")
                        .HasFilter("[Ativo] = 1");

                    b.HasIndex("RecemNascidoId", "TipoIdentificador", "Valor")
                        .IsUnique();

                    b.ToTable("PacienteIdentificador", "interoperabilidade");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.ProfissionalSaude", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GrupoSaudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroRegistro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoConselhoId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoSaudeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("TipoConselhoId");

                    b.ToTable("AspNetUsers", "core");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.ProfissionalSaudeUnidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProfissionalSaudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProfissionalSaudeId", "TenantId")
                        .IsUnique();

                    b.ToTable("ProfissionalSaudeUnidade", "core");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.RecemNascido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Apgar1Minuto")
                        .HasColumnType("int");

                    b.Property<int?>("Apgar5Minuto")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassificacaoIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassificacaoPN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ComprimentoCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoCidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoComplemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoLogradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoUf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdadeGestacionalCorrigidaDias")
                        .HasColumnType("int");

                    b.Property<decimal?>("IdadeGestacionalCorrigidaSemanas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("IdadeGestacionalDias")
                        .HasColumnType("int");

                    b.Property<decimal>("IdadeGestacionalSemanas")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PerimetroCefalicoCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("PesoNascimentoGr")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneCelular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoParto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RecemNascido", "clinica");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AtualizadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GrupoSaudeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdadePreTermoLimite")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUnidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoSaudeId");

                    b.ToTable("Tenant", "core");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.TipoConselho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoProfissional")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoConselho", "core");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Nome = "Conselho Regional de Medicina",
                            Sigla = "CRM",
                            TipoProfissional = "Médico"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Nome = "Conselho Regional de Nutricionistas",
                            Sigla = "CRN",
                            TipoProfissional = "Nutricionista"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Nome = "Conselho Regional de Enfermagem",
                            Sigla = "COREN",
                            TipoProfissional = "Enfermeiro"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Nome = "Conselho Regional de Fisioterapia e Terapia Ocupacional",
                            Sigla = "CREFITO",
                            TipoProfissional = "Fisioterapeuta"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Nome = "Conselho Regional de Farmácia",
                            Sigla = "CRF",
                            TipoProfissional = "Farmacêutico"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            Nome = "Conselho Regional de Psicologia",
                            Sigla = "CRP",
                            TipoProfissional = "Psicólogo"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            Nome = "Conselho Regional de Fonoaudiologia",
                            Sigla = "CRFa",
                            TipoProfissional = "Fonoaudiólogo"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "core");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "core");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Alimento", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.AuditoriaAcessoPaciente", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.RecemNascido", "RecemNascido")
                        .WithMany()
                        .HasForeignKey("RecemNascidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RecemNascido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Consulta", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.RecemNascido", "RecemNascido")
                        .WithMany("Consultas")
                        .HasForeignKey("RecemNascidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecemNascido");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Dieta", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.RecemNascido", "RecemNascido")
                        .WithMany()
                        .HasForeignKey("RecemNascidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecemNascido");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.DietaItem", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CrescerSaudavel.Api.Models.Dieta", "Dieta")
                        .WithMany("Itens")
                        .HasForeignKey("DietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Dieta");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.PacienteIdentificador", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.RecemNascido", "RecemNascido")
                        .WithMany("Identificadores")
                        .HasForeignKey("RecemNascidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecemNascido");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.ProfissionalSaude", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.GrupoSaude", "GrupoSaude")
                        .WithMany()
                        .HasForeignKey("GrupoSaudeId");

                    b.HasOne("CrescerSaudavel.Api.Models.Tenant", "TenantAtual")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CrescerSaudavel.Api.Models.TipoConselho", "TipoConselho")
                        .WithMany()
                        .HasForeignKey("TipoConselhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoSaude");

                    b.Navigation("TenantAtual");

                    b.Navigation("TipoConselho");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.ProfissionalSaudeUnidade", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", "ProfissionalSaude")
                        .WithMany("UnidadesPermitidas")
                        .HasForeignKey("ProfissionalSaudeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrescerSaudavel.Api.Models.Tenant", "Tenant")
                        .WithMany("Profissionais")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProfissionalSaude");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.RecemNascido", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Tenant", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.GrupoSaude", "GrupoSaude")
                        .WithMany("Unidades")
                        .HasForeignKey("GrupoSaudeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoSaude");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CrescerSaudavel.Api.Models.ProfissionalSaude", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Dieta", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.GrupoSaude", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.ProfissionalSaude", b =>
                {
                    b.Navigation("UnidadesPermitidas");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.RecemNascido", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Identificadores");
                });

            modelBuilder.Entity("CrescerSaudavel.Api.Models.Tenant", b =>
                {
                    b.Navigation("Profissionais");
                });
#pragma warning restore 612, 618
        }
    }
}
